name: Deploy Frontend

on:
  push:
    branches:
      - main   # deploy when pushing to main

jobs:
  frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install & Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy Frontend via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./frontend/dist/
          server-dir: /public_html/floorlive_frontend/

  backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Backend & Build (TypeScript → JS)
        run: |
          cd backend
          npm install
          npm run build

      - name: Prepare Backend Files for Deployment
        run: |
          mkdir -p backend-deploy
          cp -r backend/dist backend-deploy/
          cp backend/package*.json backend-deploy/
          # Copy assets directory if it exists
          if [ -d "backend/assets" ]; then
            cp -r backend/assets backend-deploy/
          fi
          # Create a simple restart file for cPanel
          echo "Backend deployed at $(date)" > backend-deploy/restart.txt

      - name: Deploy Backend via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./backend-deploy/
          server-dir: /app/floorlive_backend/
          delete-remote-dir: true