name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'shared/**'
      - '!backend/assets/**'  # Exclude assets - they have their own workflow
  workflow_dispatch:  # Allow manual triggering

jobs:
  backend:
    name: Deploy Backend Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Install Backend & Build (TypeScript → JS)
        run: |
          cd backend
          rm -rf node_modules package-lock.json
          npm install
          npm run build

      - name: Prepare Backend Files for Deployment
        run: |
          mkdir -p backend-deploy
          # Copy compiled JavaScript code
          cp -r backend/dist backend-deploy/
          # Copy package files for production dependencies
          cp backend/package*.json backend-deploy/
          # Create deployment metadata
          echo "Backend deployed at $(date)" > backend-deploy/restart.txt
          echo "Git commit: $(git rev-parse --short HEAD)" >> backend-deploy/restart.txt
          # Show what we're deploying
          echo "Backend deployment contents:"
          find backend-deploy -type f | head -20
          echo "Total backend files: $(find backend-deploy -type f | wc -l)"

      - name: Deploy Backend via FTP (Code Only - Fast!)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./backend-deploy/
          server-dir: /app/floorlive_backend/
          # Only upload changed files (git-based comparison)
          state-name: backend-deploy-state
          dry-run: false
          # Exclude files that don't need deployment
          exclude: |
            **/.git*
            **/.DS_Store
            **/Thumbs.db
            **/*.tmp
            **/*.temp
            **/node_modules/
            **/assets/  # Assets handled by separate workflow
          # Log changed files for debugging
          log-level: verbose

      - name: Restart Node.js Application in cPanel
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          script: |
            # Navigate to app directory and restart using CloudLinux Node.js Selector
            cd ~/app/floorlive_backend
            cloudlinux-selector restart --json --interpreter nodejs --app-root ~/app/floorlive_backend

      - name: Backend Deployment Summary
        run: |
          echo "🚀 Backend deployment completed!"
          echo "📦 Deployed: $(find backend-deploy -type f | wc -l) files"
          echo "💻 Commit: $(git rev-parse --short HEAD)"
          echo "🕒 Timestamp: $(date)"
          echo "⚡ Fast deployment - no assets uploaded!"